### PR TITLE
Fix in get_mask function and about HostCpusList

### PR DESCRIPTION
**Pull request by m4r1k**

### CODE REVIEW

**Comment by krsacme** [comment]
There is some issue with this get_mask function, that I am facing. 

Core List - '0,20,30,11,31,12,32'
Expected - 0x1c0101801
Existing Function Outputs - 100000000c0101801
Modified Function Outputs - 40100001

So both has issues. I am working to fix it.

**Comment by krsacme** [comment]
I have tried re-writing, still testing. If possible your inputs are welcome:

            get_mask()
            {
                list=$1
                value=0
                for core in $(echo $list | sed 's/,/ /g'); do
                    value=`echo "$value + 2^$core" | bc`
                done
                printf "%x" $value
            }

**Comment by krsacme** [comment]
@m4r1k We have updated the first-boot script again as we found some issue.

**Comment by m4r1k** [comment]
Hi there,

Sorry for the late reply but I'm at a customer site.
The new function looks good, I tested it and works like a charm.

I believe we can close this pull request given the changes in the repo :-)

Cheers

**Comment by krsacme** [comment]
@m4r1k Thanks for the feedback. Very Helpful.

**Pull request closed without merging**
